// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package slaughterhouseService;

@com.google.protobuf.Generated
public interface CutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouseService.CutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .slaughterhouseService.Part parts = 1;</code>
   */
  java.util.List<Part>
      getPartsList();
  /**
   * <code>repeated .slaughterhouseService.Part parts = 1;</code>
   */
  Part getParts(int index);
  /**
   * <code>repeated .slaughterhouseService.Part parts = 1;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .slaughterhouseService.Part parts = 1;</code>
   */
  java.util.List<? extends PartOrBuilder>
      getPartsOrBuilderList();
  /**
   * <code>repeated .slaughterhouseService.Part parts = 1;</code>
   */
  PartOrBuilder getPartsOrBuilder(
      int index);
}
