// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package slaughterhouseService;

@com.google.protobuf.Generated
public interface packHalfAnimalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.slaughterhouseService.packHalfAnimalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tray_id_1 = 1;</code>
   * @return The trayId1.
   */
  int getTrayId1();

  /**
   * <code>int32 tray_id_2 = 2;</code>
   * @return The trayId2.
   */
  int getTrayId2();
}
