// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package slaughterhouseService;

@com.google.protobuf.Generated
public interface packSingleProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.slaughterhouseService.packSingleProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tray_id = 1;</code>
   * @return The trayId.
   */
  int getTrayId();
}
