// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package slaughterhouseService;

@com.google.protobuf.Generated
public interface registerAnimalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouseService.registerAnimalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.slaughterhouseService.Animal animal = 1;</code>
   * @return Whether the animal field is set.
   */
  boolean hasAnimal();
  /**
   * <code>.slaughterhouseService.Animal animal = 1;</code>
   * @return The animal.
   */
  Animal getAnimal();
  /**
   * <code>.slaughterhouseService.Animal animal = 1;</code>
   */
  AnimalOrBuilder getAnimalOrBuilder();
}
