// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package slaughterhouseService;

@com.google.protobuf.Generated
public interface TrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:slaughterhouseService.Tray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 max_weight = 1;</code>
   * @return The maxWeight.
   */
  int getMaxWeight();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>repeated .slaughterhouseService.Part parts = 3;</code>
   */
  java.util.List<Part>
      getPartsList();
  /**
   * <code>repeated .slaughterhouseService.Part parts = 3;</code>
   */
  Part getParts(int index);
  /**
   * <code>repeated .slaughterhouseService.Part parts = 3;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .slaughterhouseService.Part parts = 3;</code>
   */
  java.util.List<? extends PartOrBuilder>
      getPartsOrBuilderList();
  /**
   * <code>repeated .slaughterhouseService.Part parts = 3;</code>
   */
  PartOrBuilder getPartsOrBuilder(
      int index);

  /**
   * <code>.slaughterhouseService.Animal animal = 4;</code>
   * @return Whether the animal field is set.
   */
  boolean hasAnimal();
  /**
   * <code>.slaughterhouseService.Animal animal = 4;</code>
   * @return The animal.
   */
  Animal getAnimal();
  /**
   * <code>.slaughterhouseService.Animal animal = 4;</code>
   */
  AnimalOrBuilder getAnimalOrBuilder();

  /**
   * <code>.slaughterhouseService.Part part = 5;</code>
   * @return Whether the part field is set.
   */
  boolean hasPart();
  /**
   * <code>.slaughterhouseService.Part part = 5;</code>
   * @return The part.
   */
  Part getPart();
  /**
   * <code>.slaughterhouseService.Part part = 5;</code>
   */
  PartOrBuilder getPartOrBuilder();

  /**
   * <code>int32 current_weight = 6;</code>
   * @return The currentWeight.
   */
  int getCurrentWeight();
}
