// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package grpc.slaughterhouseService.generate;

@com.google.protobuf.Generated
public interface cutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.slaughterhouseService.cutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * client would not input whole animal object, just the id is enough
   * </pre>
   *
   * <code>int32 animal_id = 1;</code>
   * @return The animalId.
   */
  int getAnimalId();
}
