// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package grpc.slaughterhouseService.generate;

/**
 * Protobuf type {@code com.example.slaughterhouseService.packHalfAnimalRequest}
 */
@com.google.protobuf.Generated
public final class packHalfAnimalRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.slaughterhouseService.packHalfAnimalRequest)
        packHalfAnimalRequestOrBuilder
{
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      packHalfAnimalRequest.class.getName());
  }
  // Use packHalfAnimalRequest.newBuilder() to construct.
  private packHalfAnimalRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private packHalfAnimalRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ServiceProto.internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ServiceProto.internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            packHalfAnimalRequest.class, packHalfAnimalRequest.Builder.class);
  }

  public static final int TRAY_ID_1_FIELD_NUMBER = 1;
  private int trayId1_ = 0;
  /**
   * <code>int32 tray_id_1 = 1;</code>
   * @return The trayId1.
   */
  @Override
  public int getTrayId1() {
    return trayId1_;
  }

  public static final int TRAY_ID_2_FIELD_NUMBER = 2;
  private int trayId2_ = 0;
  /**
   * <code>int32 tray_id_2 = 2;</code>
   * @return The trayId2.
   */
  @Override
  public int getTrayId2() {
    return trayId2_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (trayId1_ != 0) {
      output.writeInt32(1, trayId1_);
    }
    if (trayId2_ != 0) {
      output.writeInt32(2, trayId2_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (trayId1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, trayId1_);
    }
    if (trayId2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, trayId2_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof packHalfAnimalRequest)) {
      return super.equals(obj);
    }
    packHalfAnimalRequest other = (packHalfAnimalRequest) obj;

    if (getTrayId1()
        != other.getTrayId1()) return false;
    if (getTrayId2()
        != other.getTrayId2()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRAY_ID_1_FIELD_NUMBER;
    hash = (53 * hash) + getTrayId1();
    hash = (37 * hash) + TRAY_ID_2_FIELD_NUMBER;
    hash = (53 * hash) + getTrayId2();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static packHalfAnimalRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static packHalfAnimalRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static packHalfAnimalRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static packHalfAnimalRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static packHalfAnimalRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static packHalfAnimalRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static packHalfAnimalRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static packHalfAnimalRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static packHalfAnimalRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static packHalfAnimalRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static packHalfAnimalRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static packHalfAnimalRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(packHalfAnimalRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.slaughterhouseService.packHalfAnimalRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.slaughterhouseService.packHalfAnimalRequest)
          packHalfAnimalRequestOrBuilder
  {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServiceProto.internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServiceProto.internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              packHalfAnimalRequest.class, packHalfAnimalRequest.Builder.class);
    }

    // Construct using com.example.slaughterhouseService.packHalfAnimalRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trayId1_ = 0;
      trayId2_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ServiceProto.internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_descriptor;
    }

    @Override
    public packHalfAnimalRequest getDefaultInstanceForType() {
      return packHalfAnimalRequest.getDefaultInstance();
    }

    @Override
    public packHalfAnimalRequest build() {
      packHalfAnimalRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public packHalfAnimalRequest buildPartial() {
      packHalfAnimalRequest result = new packHalfAnimalRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(packHalfAnimalRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trayId1_ = trayId1_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.trayId2_ = trayId2_;
      }
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof packHalfAnimalRequest) {
        return mergeFrom((packHalfAnimalRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(packHalfAnimalRequest other) {
      if (other == packHalfAnimalRequest.getDefaultInstance()) return this;
      if (other.getTrayId1() != 0) {
        setTrayId1(other.getTrayId1());
      }
      if (other.getTrayId2() != 0) {
        setTrayId2(other.getTrayId2());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              trayId1_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              trayId2_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int trayId1_ ;
    /**
     * <code>int32 tray_id_1 = 1;</code>
     * @return The trayId1.
     */
    @Override
    public int getTrayId1() {
      return trayId1_;
    }
    /**
     * <code>int32 tray_id_1 = 1;</code>
     * @param value The trayId1 to set.
     * @return This builder for chaining.
     */
    public Builder setTrayId1(int value) {

      trayId1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tray_id_1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayId1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trayId1_ = 0;
      onChanged();
      return this;
    }

    private int trayId2_ ;
    /**
     * <code>int32 tray_id_2 = 2;</code>
     * @return The trayId2.
     */
    @Override
    public int getTrayId2() {
      return trayId2_;
    }
    /**
     * <code>int32 tray_id_2 = 2;</code>
     * @param value The trayId2 to set.
     * @return This builder for chaining.
     */
    public Builder setTrayId2(int value) {

      trayId2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tray_id_2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTrayId2() {
      bitField0_ = (bitField0_ & ~0x00000002);
      trayId2_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.slaughterhouseService.packHalfAnimalRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.slaughterhouseService.packHalfAnimalRequest)
  private static final packHalfAnimalRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new packHalfAnimalRequest();
  }

  public static packHalfAnimalRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<packHalfAnimalRequest>
      PARSER = new com.google.protobuf.AbstractParser<packHalfAnimalRequest>() {
    @Override
    public packHalfAnimalRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<packHalfAnimalRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<packHalfAnimalRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public packHalfAnimalRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

