// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package grpc.slaughterhouseService.generate;

/**
 * Protobuf type {@code com.example.slaughterhouseService.registerAnimalResponse}
 */
@com.google.protobuf.Generated
public final class registerAnimalResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.slaughterhouseService.registerAnimalResponse)
        registerAnimalResponseOrBuilder
{
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      registerAnimalResponse.class.getName());
  }
  // Use registerAnimalResponse.newBuilder() to construct.
  private registerAnimalResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private registerAnimalResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ServiceProto.internal_static_com_example_slaughterhouseService_registerAnimalResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ServiceProto.internal_static_com_example_slaughterhouseService_registerAnimalResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            registerAnimalResponse.class, registerAnimalResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ANIMAL_FIELD_NUMBER = 1;
  private Animal animal_;
  /**
   * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
   * @return Whether the animal field is set.
   */
  @Override
  public boolean hasAnimal() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
   * @return The animal.
   */
  @Override
  public Animal getAnimal() {
    return animal_ == null ? Animal.getDefaultInstance() : animal_;
  }
  /**
   * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
   */
  @Override
  public AnimalOrBuilder getAnimalOrBuilder() {
    return animal_ == null ? Animal.getDefaultInstance() : animal_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getAnimal());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAnimal());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof registerAnimalResponse)) {
      return super.equals(obj);
    }
    registerAnimalResponse other = (registerAnimalResponse) obj;

    if (hasAnimal() != other.hasAnimal()) return false;
    if (hasAnimal()) {
      if (!getAnimal()
          .equals(other.getAnimal())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAnimal()) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimal().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static registerAnimalResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static registerAnimalResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static registerAnimalResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static registerAnimalResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static registerAnimalResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static registerAnimalResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static registerAnimalResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static registerAnimalResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static registerAnimalResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static registerAnimalResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static registerAnimalResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static registerAnimalResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(registerAnimalResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.slaughterhouseService.registerAnimalResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.slaughterhouseService.registerAnimalResponse)
          registerAnimalResponseOrBuilder
  {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServiceProto.internal_static_com_example_slaughterhouseService_registerAnimalResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServiceProto.internal_static_com_example_slaughterhouseService_registerAnimalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              registerAnimalResponse.class, registerAnimalResponse.Builder.class);
    }

    // Construct using com.example.slaughterhouseService.registerAnimalResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetAnimalFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      animal_ = null;
      if (animalBuilder_ != null) {
        animalBuilder_.dispose();
        animalBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ServiceProto.internal_static_com_example_slaughterhouseService_registerAnimalResponse_descriptor;
    }

    @Override
    public registerAnimalResponse getDefaultInstanceForType() {
      return registerAnimalResponse.getDefaultInstance();
    }

    @Override
    public registerAnimalResponse build() {
      registerAnimalResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public registerAnimalResponse buildPartial() {
      registerAnimalResponse result = new registerAnimalResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(registerAnimalResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.animal_ = animalBuilder_ == null
            ? animal_
            : animalBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof registerAnimalResponse) {
        return mergeFrom((registerAnimalResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(registerAnimalResponse other) {
      if (other == registerAnimalResponse.getDefaultInstance()) return this;
      if (other.hasAnimal()) {
        mergeAnimal(other.getAnimal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetAnimalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Animal animal_;
    private com.google.protobuf.SingleFieldBuilder<
            Animal, Animal.Builder, AnimalOrBuilder> animalBuilder_;
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     * @return Whether the animal field is set.
     */
    public boolean hasAnimal() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     * @return The animal.
     */
    public Animal getAnimal() {
      if (animalBuilder_ == null) {
        return animal_ == null ? Animal.getDefaultInstance() : animal_;
      } else {
        return animalBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    public Builder setAnimal(Animal value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animal_ = value;
      } else {
        animalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    public Builder setAnimal(
        Animal.Builder builderForValue) {
      if (animalBuilder_ == null) {
        animal_ = builderForValue.build();
      } else {
        animalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    public Builder mergeAnimal(Animal value) {
      if (animalBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          animal_ != null &&
          animal_ != Animal.getDefaultInstance()) {
          getAnimalBuilder().mergeFrom(value);
        } else {
          animal_ = value;
        }
      } else {
        animalBuilder_.mergeFrom(value);
      }
      if (animal_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    public Builder clearAnimal() {
      bitField0_ = (bitField0_ & ~0x00000001);
      animal_ = null;
      if (animalBuilder_ != null) {
        animalBuilder_.dispose();
        animalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    public Animal.Builder getAnimalBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetAnimalFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    public AnimalOrBuilder getAnimalOrBuilder() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilder();
      } else {
        return animal_ == null ?
            Animal.getDefaultInstance() : animal_;
      }
    }
    /**
     * <code>.com.example.slaughterhouseService.Animal animal = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            Animal, Animal.Builder, AnimalOrBuilder>
        internalGetAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                Animal, Animal.Builder, AnimalOrBuilder>(
                getAnimal(),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.example.slaughterhouseService.registerAnimalResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.slaughterhouseService.registerAnimalResponse)
  private static final registerAnimalResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new registerAnimalResponse();
  }

  public static registerAnimalResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<registerAnimalResponse>
      PARSER = new com.google.protobuf.AbstractParser<registerAnimalResponse>() {
    @Override
    public registerAnimalResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<registerAnimalResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<registerAnimalResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public registerAnimalResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

