// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.31.1

package grpc.slaughterhouseService.generate;

@com.google.protobuf.Generated
public final class ServiceProto {
  private ServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_Animal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_Animal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_AnimalType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_AnimalType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_Part_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_Part_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_PartType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_PartType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_Tray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_Tray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_registerAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_registerAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_registerAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_registerAnimalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_cutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_cutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_CutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_CutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_packSingleProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_packSingleProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_PackSingleProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_PackSingleProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_slaughterhouseService_PackHalfAnimalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_slaughterhouseService_PackHalfAnimalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rservice.proto\022!com.example.slaughterho" +
      "useService\"2\n\006Animal\022\n\n\002id\030\001 \001(\005\022\016\n\006weig" +
      "ht\030\002 \001(\001\022\014\n\004type\030\003 \001(\t\"&\n\nAnimalType\022\n\n\002" +
      "id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"\\\n\004Part\022\n\n\002id\030\001 \001" +
      "(\005\022\021\n\tanimal_id\030\002 \001(\005\022\016\n\006weight\030\003 \001(\001\022\017\n" +
      "\007tray_id\030\004 \001(\005\022\024\n\014part_type_id\030\005 \001(\005\"$\n\010" +
      "PartType\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"Q\n\007Pr" +
      "oduct\022\n\n\002id\030\001 \001(\005\022\021\n\ttray_id_1\030\002 \001(\005\022\021\n\t" +
      "tray_id_2\030\003 \001(\005\022\024\n\014total_weight\030\004 \001(\001\"\350\001" +
      "\n\004Tray\022\022\n\nmax_weight\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\0226" +
      "\n\005parts\030\003 \003(\0132\'.com.example.slaughterhou" +
      "seService.Part\0229\n\006animal\030\004 \001(\0132).com.exa" +
      "mple.slaughterhouseService.Animal\0225\n\004par" +
      "t\030\005 \001(\0132\'.com.example.slaughterhouseServ" +
      "ice.Part\022\026\n\016current_weight\030\006 \001(\005\"?\n\025regi" +
      "sterAnimalRequest\022\026\n\016animal_type_id\030\001 \001(" +
      "\005\022\016\n\006weight\030\002 \001(\001\"S\n\026registerAnimalRespo" +
      "nse\0229\n\006animal\030\001 \001(\0132).com.example.slaugh" +
      "terhouseService.Animal\"\037\n\ncutRequest\022\021\n\t" +
      "animal_id\030\001 \001(\005\"E\n\013CutResponse\0226\n\005parts\030" +
      "\001 \003(\0132\'.com.example.slaughterhouseServic" +
      "e.Part\"+\n\030packSingleProductRequest\022\017\n\007tr" +
      "ay_id\030\001 \001(\005\"X\n\031PackSingleProductResponse" +
      "\022;\n\007product\030\001 \001(\0132*.com.example.slaughte" +
      "rhouseService.Product\"=\n\025packHalfAnimalR" +
      "equest\022\021\n\ttray_id_1\030\001 \001(\005\022\021\n\ttray_id_2\030\002" +
      " \001(\005\"U\n\026PackHalfAnimalResponse\022;\n\007produc" +
      "t\030\001 \001(\0132*.com.example.slaughterhouseServ" +
      "ice.Product2\233\001\n\021StationOneService\022\205\001\n\016Re" +
      "gisterAnimal\0228.com.example.slaughterhous" +
      "eService.registerAnimalRequest\0329.com.exa" +
      "mple.slaughterhouseService.registerAnima" +
      "lResponse2y\n\021StationTwoService\022d\n\003Cut\022-." +
      "com.example.slaughterhouseService.cutReq" +
      "uest\032..com.example.slaughterhouseService" +
      ".CutResponse2\256\002\n\023StationThreeService\022\216\001\n" +
      "\021PackSingleProduct\022;.com.example.slaught" +
      "erhouseService.packSingleProductRequest\032" +
      "<.com.example.slaughterhouseService.Pack" +
      "SingleProductResponse\022\205\001\n\016PackHalfAnimal" +
      "\0228.com.example.slaughterhouseService.pac" +
      "kHalfAnimalRequest\0329.com.example.slaught" +
      "erhouseService.PackHalfAnimalResponseB3\n" +
      "!com.example.slaughterhouseServiceB\014Serv" +
      "iceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_slaughterhouseService_Animal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_slaughterhouseService_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_Animal_descriptor,
        new String[] { "Id", "Weight", "Type", });
    internal_static_com_example_slaughterhouseService_AnimalType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_slaughterhouseService_AnimalType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_AnimalType_descriptor,
        new String[] { "Id", "Name", });
    internal_static_com_example_slaughterhouseService_Part_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_slaughterhouseService_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_Part_descriptor,
        new String[] { "Id", "AnimalId", "Weight", "TrayId", "PartTypeId", });
    internal_static_com_example_slaughterhouseService_PartType_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_slaughterhouseService_PartType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_PartType_descriptor,
        new String[] { "Id", "Name", });
    internal_static_com_example_slaughterhouseService_Product_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_slaughterhouseService_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_Product_descriptor,
        new String[] { "Id", "TrayId1", "TrayId2", "TotalWeight", });
    internal_static_com_example_slaughterhouseService_Tray_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_slaughterhouseService_Tray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_Tray_descriptor,
        new String[] { "MaxWeight", "Id", "Parts", "Animal", "Part", "CurrentWeight", });
    internal_static_com_example_slaughterhouseService_registerAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_slaughterhouseService_registerAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_registerAnimalRequest_descriptor,
        new String[] { "AnimalTypeId", "Weight", });
    internal_static_com_example_slaughterhouseService_registerAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_example_slaughterhouseService_registerAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_registerAnimalResponse_descriptor,
        new String[] { "Animal", });
    internal_static_com_example_slaughterhouseService_cutRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_example_slaughterhouseService_cutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_cutRequest_descriptor,
        new String[] { "AnimalId", });
    internal_static_com_example_slaughterhouseService_CutResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_example_slaughterhouseService_CutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_CutResponse_descriptor,
        new String[] { "Parts", });
    internal_static_com_example_slaughterhouseService_packSingleProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_example_slaughterhouseService_packSingleProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_packSingleProductRequest_descriptor,
        new String[] { "TrayId", });
    internal_static_com_example_slaughterhouseService_PackSingleProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_example_slaughterhouseService_PackSingleProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_PackSingleProductResponse_descriptor,
        new String[] { "Product", });
    internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_packHalfAnimalRequest_descriptor,
        new String[] { "TrayId1", "TrayId2", });
    internal_static_com_example_slaughterhouseService_PackHalfAnimalResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_example_slaughterhouseService_PackHalfAnimalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_slaughterhouseService_PackHalfAnimalResponse_descriptor,
        new String[] { "Product", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
